version: '3'
services:
  msa-db:
    build:
      context: ../
      dockerfile: build/db/Dockerfile
    image: msa-messenger-db:latest
    ports:
      - "15432:5432"
  msa-user:
    build:
      context: ../
      dockerfile: build/user/Dockerfile
    image: msa-messenger-user:latest
    ports:
      - "8080:8080"
  msa-auth:
    build:
      context: ../
      dockerfile: build/auth/Dockerfile
    image: msa-messenger-auth:latest
    ports:
      - "8081:8080"
  msa-messaging:
    build:
      context: ../
      dockerfile: build/messaging/Dockerfile
    image: msa-messenger-messaging:latest
    ports:
      - "8082:8080"
