apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-messenger-config
data:
  AUTH_GRPC_HOST_PORT: ":8090"
  AUTH_GRPC_SERVER: "msa-messenger-auth-service:8090"
  AUTH_HTTP_HOST_PORT: ":8080"
  USER_HTTP_HOST_PORT: ":8081"
  MESSAGING_HTTP_HOST_PORT: ":8082"
  DB_POSTGRES_URL: "postgres://messenger:messenger@msa-messenger-db-service/messenger?sslmode=disable"