apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-messenger-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-messenger-auth
  template:
    metadata:
      labels:
        app: msa-messenger-auth
    spec:
      containers:
      - name: msa-messenger-auth
        image: msa-messenger-auth:latest
        imagePullPolicy: "Never"
        envFrom:
        - configMapRef:
            name: msa-messenger-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1024Mi"
            cpu: "10m"
          requests:
            memory: "1024Mi"
            cpu: "5m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-messenger-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-messenger-user
  template:
    metadata:
      labels:
        app: msa-messenger-user
    spec:
      containers:
      - name: msa-messenger-user
        imagePullPolicy: "Never"
        image: msa-messenger-user:latest
        envFrom:
        - configMapRef:
            name: msa-messenger-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1024Mi"
            cpu: "10m"
          requests:
            memory: "1024Mi"
            cpu: "5m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-messenger-messaging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-messenger-messaging
  template:
    metadata:
      labels:
        app: msa-messenger-messaging
    spec:
      containers:
      - name: msa-messenger-messaging
        imagePullPolicy: "Never"
        image: msa-messenger-messaging:latest
        envFrom:
        - configMapRef:
            name: msa-messenger-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1024Mi"
            cpu: "10m"
          requests:
            memory: "1024Mi"
            cpu: "5m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1