// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: api/auth/service.proto

package auth_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenVerifyService_VerifyToken_FullMethodName = "/auth_proto.TokenVerifyService/VerifyToken"
)

// TokenVerifyServiceClient is the client API for TokenVerifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenVerifyServiceClient interface {
	VerifyToken(ctx context.Context, in *TokenVerificationRequest, opts ...grpc.CallOption) (*TokenVerificationResponse, error)
}

type tokenVerifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenVerifyServiceClient(cc grpc.ClientConnInterface) TokenVerifyServiceClient {
	return &tokenVerifyServiceClient{cc}
}

func (c *tokenVerifyServiceClient) VerifyToken(ctx context.Context, in *TokenVerificationRequest, opts ...grpc.CallOption) (*TokenVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenVerificationResponse)
	err := c.cc.Invoke(ctx, TokenVerifyService_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenVerifyServiceServer is the server API for TokenVerifyService service.
// All implementations must embed UnimplementedTokenVerifyServiceServer
// for forward compatibility.
type TokenVerifyServiceServer interface {
	VerifyToken(context.Context, *TokenVerificationRequest) (*TokenVerificationResponse, error)
	mustEmbedUnimplementedTokenVerifyServiceServer()
}

// UnimplementedTokenVerifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenVerifyServiceServer struct{}

func (UnimplementedTokenVerifyServiceServer) VerifyToken(context.Context, *TokenVerificationRequest) (*TokenVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedTokenVerifyServiceServer) mustEmbedUnimplementedTokenVerifyServiceServer() {}
func (UnimplementedTokenVerifyServiceServer) testEmbeddedByValue()                            {}

// UnsafeTokenVerifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenVerifyServiceServer will
// result in compilation errors.
type UnsafeTokenVerifyServiceServer interface {
	mustEmbedUnimplementedTokenVerifyServiceServer()
}

func RegisterTokenVerifyServiceServer(s grpc.ServiceRegistrar, srv TokenVerifyServiceServer) {
	// If the following call pancis, it indicates UnimplementedTokenVerifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenVerifyService_ServiceDesc, srv)
}

func _TokenVerifyService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenVerifyServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenVerifyService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenVerifyServiceServer).VerifyToken(ctx, req.(*TokenVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenVerifyService_ServiceDesc is the grpc.ServiceDesc for TokenVerifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenVerifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_proto.TokenVerifyService",
	HandlerType: (*TokenVerifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _TokenVerifyService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/service.proto",
}
