apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-db-config
data:
  POSTGRES_USER: "messenger"
  POSTGRES_PASSWORD: "messenger"
  POSTGRES_DB: "messenger"
  POSTGRES_INITDB_ARGS: "--encoding=UTF8"
  POSTGRES_HOST_AUTH_METHOD: "password"
  PGDATA: "/data/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: msa-db-pv
spec:
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/tmp/msa/postgres/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msa-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi