apiVersion: v1
kind: Service
metadata:
  name: msa-messenger-db-service
spec:
  selector:
    app: msa-messenger-db
  type: NodePort
  ports:
    - port: 5432
      # targetPort: 5432
      # protocol: TCP